# Generated by Django 5.2.1 on 2025-08-14 08:11

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Firma nomi')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz ismi')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('client_due_date', models.DateField(blank=True, null=True, verbose_name="To'lov muddati")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('total_price', models.IntegerField(default=0, verbose_name='Umumiy narx')),
                ('paid_amount', models.IntegerField(default=0, verbose_name="To'langan summa")),
                ('pending_amount', models.IntegerField(default=0, verbose_name="Kutilayotgan to'lov")),
                ('remaining_amount', models.IntegerField(default=0, verbose_name='Qolgan qarz')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('partial', "Qisman to'langan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=99, scale=None, size=[60, 60], upload_to='seller/%Y/%m', verbose_name='Maxsulot rasmi')),
                ('first_name', models.CharField(max_length=40, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=40, verbose_name='Familyasi')),
                ('phone_number', models.IntegerField(verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=99, scale=None, size=[40, 40], upload_to='slider/%Y/%m', verbose_name='Maxsulot rasmi')),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('entry_price', models.IntegerField(verbose_name='Tan narxi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('max_discount', models.IntegerField(verbose_name='maksimal chagirma')),
                ('amount', models.IntegerField(verbose_name='Miqdori')),
                ('date_published', models.DateField(verbose_name='Sanasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='common.productcategory', verbose_name='Maxsulot firmasi')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('credit', 'Nasiya'), ('bank_transfer', "Bank o'tkazmasi")], max_length=20, verbose_name="To'lov turi")),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdor')),
                ('price', models.IntegerField(verbose_name='Narx')),
                ('discount', models.IntegerField(default=0, verbose_name='Chegirma')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Jami')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv mahsuloti',
                'verbose_name_plural': 'Sotuv mahsulotlari',
            },
        ),
    ]
