# Generated by Django 5.2.1 on 2025-08-15 17:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'Kassa kategoriyasi',
                'verbose_name_plural': 'Kassa kategoriyalari',
                'db_table': 'Kassa kategoriyasi',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Firma nomi')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'db_table': 'product_category',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=99, scale=None, size=[60, 60], upload_to='seller/%Y/%m', verbose_name='Maxsulot rasmi')),
                ('first_name', models.CharField(max_length=40, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=40, verbose_name='Familyasi')),
                ('phone_number', models.IntegerField(verbose_name='Telefon raqami')),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=256, verbose_name='phone')),
                ('role', models.CharField(choices=[('manager', 'manager'), ('cashier', 'kassir'), ('seller', 'sotuvchi')], max_length=256, verbose_name='role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('seller_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='common.seller')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ochilgan vaqti')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqti')),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Naqd summa')),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Karta summa')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy tushum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Kassa egasi')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=10, verbose_name='Turi')),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('created_at', models.DateTimeField(verbose_name='Sana')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.cashflowcategory', verbose_name='kategoriya')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='common.cashregister', verbose_name='Kassa')),
            ],
            options={
                'verbose_name': 'Kassa harakati',
                'verbose_name_plural': 'Kassa harakatlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=99, scale=None, size=[40, 40], upload_to='slider/%Y/%m', verbose_name='Maxsulot rasmi')),
                ('name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('entry_price', models.IntegerField(verbose_name='Tan narxi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('max_discount', models.IntegerField(verbose_name='maksimal chagirma')),
                ('amount', models.IntegerField(verbose_name='Miqdori')),
                ('date_published', models.DateField(verbose_name='Sanasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='common.productcategory', verbose_name='Maxsulot firmasi')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz ismi')),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('client_due_date', models.DateField(blank=True, null=True, verbose_name="To'lov muddati")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('total_price', models.IntegerField(default=0, verbose_name='Umumiy narx')),
                ('paid_amount', models.IntegerField(default=0, verbose_name="To'langan summa")),
                ('pending_amount', models.IntegerField(default=0, verbose_name="Kutilayotgan to'lov")),
                ('remaining_amount', models.IntegerField(default=0, verbose_name='Qolgan qarz')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('partial', "Qisman to'langan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Status')),
                ('cash_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='common.cashregister')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('credit', 'Nasiya'), ('bank_transfer', "Bank o'tkazmasi")], max_length=20, verbose_name="To'lov turi")),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdor')),
                ('price', models.IntegerField(verbose_name='Narx')),
                ('discount', models.IntegerField(default=0, verbose_name='Chegirma')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Jami')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv mahsuloti',
                'verbose_name_plural': 'Sotuv mahsulotlari',
            },
        ),
    ]
