# Generated by Django 5.2.1 on 2025-08-07 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='cash_amount',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='credit_amount',
            new_name='remaining_amount',
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('partial', "Qisman to'langan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.sale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('credit', 'Nasiya'), ('bank_transfer', "Bank o'tkazmasi")], max_length=20)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.sale')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
