# Generated by Django 5.2.1 on 2025-08-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sale_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kassa nomi')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Balans')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ochiqmi')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Ochilish vaqti')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilish vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Kassa egasi')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='common.cashregister', verbose_name='Kassa'),
        ),
    ]
