# Generated by Django 5.2.1 on 2025-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_cash_amount_sale_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='cash_amount',
            field=models.IntegerField(default=0),
        ),
    ]
