# Generated by Django 5.2.1 on 2025-08-14 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_cashregister_sale_cash_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sal', to='common.cashregister', verbose_name='Kassa'),
        ),
    ]
