# Generated by Django 5.2.1 on 2025-08-09 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_payment_cash_amount_sale_cash_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Sotuv', 'verbose_name_plural': 'Sotuvlar'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Sotuv mahsuloti', 'verbose_name_plural': 'Sotuv mahsulotlari'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='cash_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cash_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('credit', 'Nasiya'), ('bank_transfer', "Bank o'tkazmasi")], max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.sale', verbose_name='Sotuv'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_due_date',
            field=models.DateField(blank=True, null=True, verbose_name="To'lov muddati"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz ismi'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paid_amount',
            field=models.IntegerField(default=0, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='sale',
            name='remaining_amount',
            field=models.IntegerField(default=0, verbose_name='Qolgan qarz'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('paid', "To'langan"), ('partial', "Qisman to'langan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Chegirma'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.IntegerField(verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.sale', verbose_name='Sotuv'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jami'),
        ),
    ]
