# Generated by Django 5.2.1 on 2025-08-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_payment_options_alter_sale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pending_amount',
            field=models.IntegerField(default=0, verbose_name="Kutilyotkan to'lov"),
        ),
    ]
