# Generated by Django 5.2.1 on 2025-08-14 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_sale_cash_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cash_register',
        ),
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
