# Generated by Django 5.2.1 on 2025-08-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_sale_pending_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.AlterField(
            model_name='sale',
            name='pending_amount',
            field=models.IntegerField(default=0, verbose_name="Kutilayotgan to'lov"),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
