# Generated by Django 5.2.1 on 2025-08-09 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_saleitem_product_remove_saleitem_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('credit', 'Nasiya'), ('bank_transfer', "Bank o'tkazmasi")], max_length=20, verbose_name="To'lov turi")),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='common.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdor')),
                ('price', models.IntegerField(verbose_name='Narx')),
                ('discount', models.IntegerField(default=0, verbose_name='Chegirma')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='Jami')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.product', verbose_name='Mahsulot')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='common.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv mahsuloti',
                'verbose_name_plural': 'Sotuv mahsulotlari',
            },
        ),
    ]
