# Generated by Django 5.2.1 on 2025-08-14 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_sale_user_delete_cashregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ochilgan vaqti')),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Naqd summa')),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Karta summa')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy tushum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to=settings.AUTH_USER_MODEL, verbose_name='Kassa egasi')),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
            },
        ),
    ]
