# Generated by Django 5.2.1 on 2025-08-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_cashregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='total_card',
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='total_cash',
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='total_sales',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqti'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Boshlang'ich balans"),
        ),
    ]
