# Generated by Django 5.2.1 on 2025-08-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_cashregister_total_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashregister',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='opening_balance',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='total_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Karta summa'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Naqd summa'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Umumiy tushum'),
        ),
    ]
