# Generated by Django 5.2.1 on 2025-08-15 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_cashregister_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='closed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yopilgan vaqti'),
        ),
    ]
