# Generated by Django 5.2.1 on 2025-08-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_cashregister_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash', to='common.cashregister'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqti'),
        ),
    ]
